name: upload to google cloud storage

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  cypress-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-actions@v5

  deploy-storage:
    needs: [cypress-test]
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          service_account: "my-service-account@my-project.iam.gserviceaccount.com"

      - id: "upload-folder"
        uses: "google-github-actions/upload-cloud-storage@v1"
        with:
          path: "/path/to/folder"
          destination: "bucket-name"

      # Example of using the output
      - id: "uploaded-files"
        uses: "foo/bar@main"
        env:
          files: "${{ steps.upload-folder.outputs.uploaded }}"
